[PHP]
max_execution_time = 300
max_input_time = 60
memory_limit = 512M
upload_max_filesize = 256M
post_max_size = 256M
default_charset = "UTF-8"
date.timezone = "UTC"

[OpCache]
opcache.enable = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.max_wasted_percentage = 5
opcache.consistency_checks = 0

[Display]
display_errors = Off
log_errors = On
error_log = /var/log/php/error.log
