#!/bin/bash
# Script de configuration Jenkins pour GitHub Integration

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  🤖 CONFIGURATION JENKINS POUR GITHUB                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"

# Récupérer l'URL Jenkins
JENKINS_URL=${1:-"http://localhost:8084"}

echo ""
echo "📍 Jenkins URL: $JENKINS_URL"
echo ""
echo "INSTALLATION MANUELLE DES PLUGINS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Aller à: $JENKINS_URL/manage/pluginManager/available"
echo ""
echo "2. Rechercher et installer:"
echo "   ✓ GitHub Integration Plugin"
echo "   ✓ GitHub Branch Source Plugin"
echo "   ✓ GitHub API Plugin"
echo "   ✓ SSH Agent Plugin"
echo "   ✓ Credentials Plugin"
echo ""

echo "CONFIGURATION DES CREDENTIALS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Aller à: $JENKINS_URL/manage/credentials"
echo ""
echo "2. Ajouter une credential:"
echo ""
echo "   Type: Username with password"
echo "   Username: votre_username_github"
echo "   Password: votre_personal_access_token (ou mot de passe GitHub)"
echo "   ID: github-credentials"
echo "   Description: GitHub Credentials for Drupal CI/CD"
echo ""
echo "3. Ajouter un secret texte:"
echo ""
echo "   Type: Secret text"
echo "   Secret: votre_personal_access_token"
echo "   ID: github-token"
echo "   Description: GitHub API Token"
echo ""
echo "4. Ajouter une clé SSH:"
echo ""
echo "   Type: SSH Username with private key"
echo "   Username: deploy (ou votre utilisateur SSH serveur)"
echo "   Private key: <contenu de la clé privée de déploiement>"
echo "   ID: deploy-key"
echo "   Description: Server SSH Deploy Key"
echo ""

echo "CRÉER UN NOUVEAU JOB PIPELINE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Aller à: $JENKINS_URL"
echo ""
echo "2. Créer un nouveau job:"
echo "   - New Item"
echo "   - Nom: drupal-pipeline"
echo "   - Type: Pipeline"
echo ""
echo "3. Configuration du job:"
echo "   - GitHub project: https://github.com/YOUR_USERNAME/drupal"
echo "   - Build Triggers:"
echo "     ✓ Poll SCM: H H * * * (une fois par jour)"
echo "     ✓ GitHub hook trigger: [PUSH et PR]"
echo ""
echo "4. Pipeline Definition:"
echo "   - Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: https://github.com/YOUR_USERNAME/drupal.git"
echo "   - Branch: */develop, */main"
echo "   - Script Path: Jenkinsfile"
echo ""
echo "5. GitHub WebHook:"
echo "   - Dans Jenkins: $JENKINS_URL/github-webhook/"
echo "   - Dans GitHub Repo Settings:"
echo "     * Settings > Webhooks > Add webhook"
echo "     * Payload URL: $JENKINS_URL/github-webhook/"
echo "     * Content type: application/json"
echo "     * Triggers: Push events, Pull requests"
echo ""

echo "PERSONAL ACCESS TOKEN (GitHub):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Générer un token:"
echo "1. GitHub.com > Settings > Developer settings > Personal access tokens"
echo "2. Generate new token"
echo "3. Scopes nécessaires:"
echo "   ✓ repo (Full control of private repositories)"
echo "   ✓ admin:repo_hook (Full control of repository hooks)"
echo "   ✓ admin:org_hook (Full control of organization hooks)"
echo "   ✓ workflow (Update GitHub Action workflows)"
echo ""

echo "ENVIRONNEMENT VARIABLES DANS JENKINS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ajouter dans Configure System:"
echo "   DB_HOST: mariadb (ou votre host)"
echo "   DB_USER: drupal"
echo "   DB_PASSWORD: drupal"
echo "   DB_NAME: drupal"
echo "   DRUPAL_ENV: develop/staging/production"
echo "   SERVER_IP: IP du serveur cible"
echo "   DEPLOY_PATH: /var/www/drupal-production"
echo "   DEPLOY_USER: deploy"
echo ""

echo "VÉRIFICATION DU SETUP:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Plugins installés et activés"
echo "✓ Credentials configurées"
echo "✓ WebHook GitHub configuré"
echo "✓ Jenkinsfile présent dans le repo"
echo "✓ Scripts de build/deploy accessibles"
echo ""
echo "✅ Configuration Jenkins terminée!"
echo ""
